Combat NPC recode
HorizonsEndMC/Ion pull request #256
Opened 2023-02-16 21:08 UTC by Rattlyy

Recodes Combat NPCs to actually work. Tested with Sciath.

2023-02-16 22:12 UTC, trainb0y commented on server/src/main/kotlin/net/horizonsend/ion/server/features/combatnpcs/CombatNPCs.kt
> +	// CREDITS TO TRAINBOY
You don’t need to credit me like this lol

2023-02-22 02:40 UTC, Peter-Crawley commented
Rebase required

2023-02-24 09:11 UTC, Peter-Crawley requested changes

2023-02-24 09:11 UTC, Peter-Crawley commented on server/src/main/kotlin/net/horizonsend/ion/server/features/combatnpcs/CombatNPCs.kt
> +import java.util.*
no wildcards

2023-03-21 14:35 UTC, Peter-Crawley commented
merge conficts

2023-04-07 17:25 UTC, closed without merging