Custom Item Rework
HorizonsEndMC/Ion pull request #72
Opened 2022-01-09 19:26 UTC by trainb0y1

Oh boy, this is gonna be a long one.

- Broke up the giant `customitems.kt` and `customrecipes.kt` files
- Register custom items and recipes in the same place
- Custom item identification is based on PDC, not CMD
- Basic "API" for custom items, providing hooks for actions such as `onRightClick()`, `onLeftClick()` and `onDrop()` without having to register another listener
- Moved drill, energy sword, and blaster functionality out of external listeners
- Moved `DoubleJumpListener` out of the `gear` package (deleted `gear` package)
- If an ItemStack is a custom item it can now be accessed through `ItemStack.customItem`
- Added `get` subcommand for `/battery` for the sake of debugging
- Enchants on custom items can be enabled on an item by item basis, otherwise they are unenchantable
- All custom item related code is now in the `net.starlegacy.feature.customitem` package
- Improvements to item power
    - Power is now accessed through `ItemStack.power` extension property instead of functions like `addPower(itemStack, power)` and `getPower(itemStack)`
    - Item power now uses PDC, not lore
    - Item power is now represented in the durability bar
    - Items out of power do not break. 
- Added a "uses" system
    - `/uses` command with the same syntax as `/battery`
    - Some powerable items (currently blasters) have a usage counter. Each time they are used it goes down by one, when it reaches zero the ItemStack loses an item.
    - This can be thought of as "true durability" and acts as a very minor resource sink
 - Reworked power armor
    - Brought over MSP's power armor system, with some tweaks.
    - `/powerarmor` command opens a GUI into which the player can add or remove modules.
    - The GUI cannot be opened if the player was recently in combat
    - Each module has a weight value, and a player's total module weight cannot exceed a certain maximum. If it does, their armor disables.
    - Ported SL's Rocket Boosting, Speed Boosting, and Night Vision modules.
    - Armor pieces are standard powerable items, but a player's armor power is considered to be the sum of all the armor piece power.
    - Armor modules are not armor piece specific
    - Power armor does not function unless the player is wearing a full set
    - In addition to charging the items themselves, the player can drag batteries, or other powerable items, into a power slot in the GUI, depleting their power and charging the armor.
   

**ALL EXISTING CUSTOM ITEMS WILL CEASE TO FUNCTION**

I won't claim that this code is in any way neat, orderly, clean, efficient, or any other positive attribute. 
I also do not claim that the new power armor or usage system is at all balanced, that is up to the balancing team to fix.

2022-01-09 19:28 UTC, PiggleMcDiggle commented
Peter, _glhf_...

2022-01-09 19:29 UTC, trainb0y1 commented
There's definitely some stuff I need to fix so if you guys could point me in the right direction that would be great.

2022-01-09 19:38 UTC, Peter-Crawley requested changes
Based on my first glance on github, this looks good. I am gonna have to look through and test this properly though.

2022-01-09 19:38 UTC, Peter-Crawley commented on server/StarLegacy/src/main/kotlin/net/starlegacy/StarLegacy.kt
> +import net.starlegacy.command.misc.*
be gone * import

2022-01-09 19:38 UTC, Peter-Crawley commented on server/StarLegacy/src/main/kotlin/net/starlegacy/command/misc/ItemUsesCommand.kt
> +package net.starlegacy.command.misc
New files should be in the Ion folder

2022-01-09 19:38 UTC, Peter-Crawley commented on server/StarLegacy/src/main/kotlin/net/starlegacy/command/misc/PowerArmorCommand.kt
> +package net.starlegacy.command.misc
New files should be in the Ion folder

2022-01-09 19:38 UTC, Peter-Crawley commented on server/StarLegacy/src/main/kotlin/net/starlegacy/feature/customitem/BatteryItems.kt
> +package net.starlegacy.feature.customitem
New files should be in the Ion folder

2022-01-09 19:38 UTC, Peter-Crawley commented on server/StarLegacy/src/main/kotlin/net/starlegacy/feature/customitem/CustomItems.kt
> +package net.starlegacy.feature.customitem
New files should be in the Ion folder

2022-01-09 19:38 UTC, Peter-Crawley commented on server/StarLegacy/src/main/kotlin/net/starlegacy/feature/customitem/EnergySwords.kt
> +package net.starlegacy.feature.customitem
New files should be in the Ion folder

2022-01-09 19:38 UTC, Peter-Crawley commented on server/StarLegacy/src/main/kotlin/net/starlegacy/feature/customitem/GasItems.kt
> +package net.starlegacy.feature.customitem
New files should be in the Ion folder

2022-01-09 19:38 UTC, Peter-Crawley commented on server/StarLegacy/src/main/kotlin/net/starlegacy/feature/customitem/Minerals.kt
> +package net.starlegacy.feature.customitem
New files should be in the Ion folder

2022-01-09 19:38 UTC, Peter-Crawley commented on server/StarLegacy/src/main/kotlin/net/starlegacy/feature/customitem/MiscItems.kt
> +package net.starlegacy.feature.customitem
New files should be in the Ion folder

2022-01-09 19:38 UTC, Peter-Crawley commented on server/StarLegacy/src/main/kotlin/net/starlegacy/feature/customitem/MiscRecipes.kt
> +package net.starlegacy.feature.customitem
New files should be in the Ion folder

2022-01-09 19:38 UTC, Peter-Crawley commented on server/StarLegacy/src/main/kotlin/net/starlegacy/feature/customitem/PlanetIcons.kt
> +package net.starlegacy.feature.customitem
New files should be in the Ion folder

2022-01-09 19:38 UTC, Peter-Crawley commented on server/StarLegacy/src/main/kotlin/net/starlegacy/feature/customitem/RocketItems.kt
> +package net.starlegacy.feature.customitem
New files should be in the Ion folder

2022-01-09 19:38 UTC, Peter-Crawley commented on server/StarLegacy/src/main/kotlin/net/starlegacy/feature/customitem/ToolItems.kt
> +package net.starlegacy.feature.customitem
New files should be in the Ion folder

2022-01-09 19:38 UTC, Peter-Crawley commented on server/StarLegacy/src/main/kotlin/net/starlegacy/feature/customitem/blaster/BlasterItems.kt
> +package net.starlegacy.feature.customitem.blaster
New files should be in the Ion folder

2022-01-09 19:38 UTC, Peter-Crawley commented on server/StarLegacy/src/main/kotlin/net/starlegacy/feature/customitem/powerarmor/ArmorActivatorRunnable.kt
> +package net.starlegacy.feature.customitem.powerarmor
New files should be in the Ion folder

2022-01-09 19:38 UTC, Peter-Crawley commented on server/StarLegacy/src/main/kotlin/net/starlegacy/feature/customitem/powerarmor/ModuleScreen.kt
> +package net.starlegacy.feature.customitem.powerarmor
New files should be in the Ion folder

2022-01-09 19:38 UTC, Peter-Crawley commented on server/StarLegacy/src/main/kotlin/net/starlegacy/feature/customitem/powerarmor/PowerArmor.kt
> +package net.starlegacy.feature.customitem.powerarmor
New files should be in the Ion folder

2022-01-09 19:38 UTC, Peter-Crawley commented on server/StarLegacy/src/main/kotlin/net/starlegacy/feature/customitem/powerarmor/PowerArmorItems.kt
> +package net.starlegacy.feature.customitem.powerarmor
New files should be in the Ion folder

2022-01-09 19:38 UTC, Peter-Crawley commented on server/StarLegacy/src/main/kotlin/net/starlegacy/feature/customitem/powerarmor/PowerModuleItems.kt
> +package net.starlegacy.feature.customitem.powerarmor
New files should be in the Ion folder

2022-01-09 19:38 UTC, Peter-Crawley commented on server/StarLegacy/src/main/kotlin/net/starlegacy/feature/customitem/powerarmor/modules/PotionEffectModule.kt
> +package net.starlegacy.feature.customitem.powerarmor.modules
New files should be in the Ion folder

2022-01-09 19:38 UTC, Peter-Crawley commented on server/StarLegacy/src/main/kotlin/net/starlegacy/feature/customitem/powerarmor/modules/PowerArmorModule.kt
> +package net.starlegacy.feature.customitem.powerarmor.modules
New files should be in the Ion folder

2022-01-09 19:38 UTC, Peter-Crawley commented on server/StarLegacy/src/main/kotlin/net/starlegacy/feature/customitem/powerarmor/modules/RocketModule.kt
> +package net.starlegacy.feature.customitem.powerarmor.modules
New files should be in the Ion folder

2022-01-09 19:38 UTC, Peter-Crawley commented on server/StarLegacy/src/main/kotlin/net/starlegacy/feature/customitem/powerarmor/modules/SpeedModule.kt
> +package net.starlegacy.feature.customitem.powerarmor.modules
New files should be in the Ion folder

2022-01-09 19:38 UTC, Peter-Crawley commented on server/StarLegacy/src/main/kotlin/net/starlegacy/feature/customitem/type/BatteryItem.kt
> +package net.starlegacy.feature.customitem.type
New files should be in the Ion folder

2022-01-09 19:38 UTC, Peter-Crawley commented on server/StarLegacy/src/main/kotlin/net/starlegacy/feature/customitem/type/BlasterItem.kt
> +package net.starlegacy.feature.customitem.type
New files should be in the Ion folder

2022-01-09 19:38 UTC, Peter-Crawley commented on server/StarLegacy/src/main/kotlin/net/starlegacy/feature/customitem/type/BreakablePowerItem.kt
> +package net.starlegacy.feature.customitem.type
New files should be in the Ion folder

2022-01-09 19:38 UTC, Peter-Crawley commented on server/StarLegacy/src/main/kotlin/net/starlegacy/feature/customitem/type/CustomBlockItem.kt
> +package net.starlegacy.feature.customitem.type
New files should be in the Ion folder

2022-01-09 19:38 UTC, Peter-Crawley commented on server/StarLegacy/src/main/kotlin/net/starlegacy/feature/customitem/type/CustomItem.kt
> +package net.starlegacy.feature.customitem.type
New files should be in the Ion folder

2022-01-09 19:38 UTC, Peter-Crawley commented on server/StarLegacy/src/main/kotlin/net/starlegacy/feature/customitem/type/DrillItem.kt
> +package net.starlegacy.feature.customitem.type
New files should be in the Ion folder

2022-01-09 19:38 UTC, Peter-Crawley commented on server/StarLegacy/src/main/kotlin/net/starlegacy/feature/customitem/type/EnergySwordItem.kt
> +package net.starlegacy.feature.customitem.type
New files should be in the Ion folder

2022-01-09 19:38 UTC, Peter-Crawley commented on server/StarLegacy/src/main/kotlin/net/starlegacy/feature/customitem/type/GasItem.kt
> +package net.starlegacy.feature.customitem.type
New files should be in the Ion folder

2022-01-09 19:38 UTC, Peter-Crawley commented on server/StarLegacy/src/main/kotlin/net/starlegacy/feature/customitem/type/GenericCustomItem.kt
> +package net.starlegacy.feature.customitem.type
New files should be in the Ion folder

2022-01-09 19:38 UTC, Peter-Crawley commented on server/StarLegacy/src/main/kotlin/net/starlegacy/feature/customitem/type/MineralItem.kt
> +package net.starlegacy.feature.customitem.type
New files should be in the Ion folder

2022-01-09 19:38 UTC, Peter-Crawley commented on server/StarLegacy/src/main/kotlin/net/starlegacy/feature/customitem/type/PowerArmorItem.kt
> +package net.starlegacy.feature.customitem.type
New files should be in the Ion folder

2022-01-09 19:38 UTC, Peter-Crawley commented on server/StarLegacy/src/main/kotlin/net/starlegacy/feature/customitem/type/PowerItem.kt
> +package net.starlegacy.feature.customitem.type
New files should be in the Ion folder

2022-01-09 19:38 UTC, Peter-Crawley commented on server/StarLegacy/src/main/kotlin/net/starlegacy/util/Screen.kt
> +package net.starlegacy.util
New files should be in the Ion folder

2022-01-09 19:39 UTC, trainb0y1 commented on server/StarLegacy/src/main/kotlin/net/starlegacy/StarLegacy.kt
> +import net.starlegacy.command.misc.*
Oh lol didn't see that

2022-01-09 20:11 UTC, Peter-Crawley requested changes

2022-01-09 20:11 UTC, Peter-Crawley commented on server/StarLegacy/src/main/kotlin/net/starlegacy/util/Screen.kt
> +abstract class Screen : Listener {
Use inventory framework instead

2022-01-09 22:38 UTC, trainb0y1 commented on server/StarLegacy/src/main/kotlin/net/starlegacy/util/Screen.kt
> +abstract class Screen : Listener {
https://discord.com/channels/916891217596395631/916921073193320448/929864826182828092

2022-01-16 04:43 UTC, trainb0y1 commented
Gonna pull a Sciath here and beg for this to be merged. The longer this has on the server before release, the more time there is to iron out bugs. 

If it’s not going to be merged, that’s fine, but I’d like some closure on this lol.

2022-01-16 14:26 UTC, Peter-Crawley requested changes

2022-01-16 14:26 UTC, Peter-Crawley commented on server/Ion/src/main/kotlin/net/horizonsend/ion/server/powerarmor/ModuleScreen.kt
> +			playerEditableSlots.addAll(mutableSetOf(0, 1, 2, 3, 9, 10, 11, 12, 18, 19, 20, 21, 26))
This would probably be better as a set, not a mutable set as it does not need to be edited.

2022-01-16 14:26 UTC, Peter-Crawley commented on server/Ion/src/main/kotlin/net/horizonsend/ion/server/powerarmor/PowerArmor.kt
> +		val moduleCSV = persistentDataContainer.get(
Why is this being done as CSV? PDC does support lists and dictionary, it's just an absolute nightmare.

An example of there implementation can be found in the old MSP code:
https://github.com/Peter-Crawley/Minecraft-Starship-Plugin/blob/multiblocks/src/main/kotlin/multiblocks/MultiblockPDC.kt
https://github.com/Peter-Crawley/Minecraft-Starship-Plugin/blob/431598274369ea9e8a7ddec1d41e7bed0145979f/src/main/kotlin/multiblocks/MultiblockListener.kt#L95
https://github.com/Peter-Crawley/Minecraft-Starship-Plugin/blob/431598274369ea9e8a7ddec1d41e7bed0145979f/src/main/kotlin/multiblocks/MultiblockListener.kt#L103

2022-01-16 14:26 UTC, Peter-Crawley commented on server/Ion/src/main/kotlin/net/horizonsend/ion/server/powerarmor/modules/SpeedModule.kt
> +		return lastMoved.containsKey(player.uniqueId) && Instant.now().toEpochMilli() - (lastMoved[player.uniqueId]
What's with `Instant.now().toEpochMilli()`, isnt `System.currentTimeMillis()` sufficient?

2022-01-16 14:26 UTC, Peter-Crawley commented on server/StarLegacy/src/main/kotlin/net/starlegacy/feature/customitem/blaster/BlasterProjectile.kt
> +					block.setType(Material.AIR, false)
Import enums directly

2022-01-16 15:00 UTC, trainb0y1 commented on server/Ion/src/main/kotlin/net/horizonsend/ion/server/powerarmor/modules/SpeedModule.kt
> +		return lastMoved.containsKey(player.uniqueId) && Instant.now().toEpochMilli() - (lastMoved[player.uniqueId]
That was how it was done in the original power armor. I’ll change that though.

2022-01-16 15:01 UTC, trainb0y1 commented on server/Ion/src/main/kotlin/net/horizonsend/ion/server/powerarmor/PowerArmor.kt
> +		val moduleCSV = persistentDataContainer.get(
Huh, I didn’t know. I’ll take a look.

2022-01-21 23:35 UTC, Peter-Crawley approved these changes
This looks good, will test properly soon. Probably on a development stream.

2022-01-21 23:56 UTC, trainb0y1 commented
Sweet. I didn’t get around to testing things like gas collectors and hyperdrives, so if there are major issues it’s probably there

2022-01-22 15:09 UTC, trainb0y1 commented
Forgot to mention that I didn't test Energy Swords, as that's hard to do with only one person. I mostly just copy/pasted that part of the code though, so it *should* be fine.

2022-01-23 16:48 UTC, Peter-Crawley requested changes
Some issues found during testing yesterday:
- GUI is opened when you right click when holding armour
- No colouring on the item names
- Modules should list how much weight they take up

2022-01-23 22:07 UTC, trainb0y1 commented
> * GUI is opened when you right click when holding armour

Fixed with 4d0e25abe6e01efb8c6f7a1d99cf04bc100368b0

2022-01-23 22:18 UTC, trainb0y1 commented
>  * Modules should list how much weight they take up

Fixed (albeit in a sloppy way) with 48d642d9c3e7316bd4005ce05d4609aec087475c

2022-01-23 22:45 UTC, trainb0y1 commented
>   * No colouring on the item names  

Will probably get to this tomorrow

2022-01-23 22:46 UTC, trainb0y1 commented
Should I do this? https://github.com/HorizonsEndMC/Ion/issues/79#issuecomment-1019581763

2022-01-24 23:52 UTC, trainb0y1 commented
I'm a little confused as to why this is causing issues now, when it didn't before I merged main with e1a5265c96ac48963006b0ed83c31200928194e3
![image](https://user-images.githubusercontent.com/66213737/150884483-63c5b6d5-ecf5-4f5c-b1db-024ecceae3dc.png)
  
  
I look at what it's complaining about and all three are 
![image](https://user-images.githubusercontent.com/66213737/150884536-bee5f3ee-bdd5-41f7-99ff-4484486c5478.png)

I'm more than a little confused

2022-01-25 14:56 UTC, Peter-Crawley commented
> Should I do this? [#79 (comment)](https://github.com/HorizonsEndMC/Ion/issues/79#issuecomment-1019581763)

No

2022-01-25 14:57 UTC, Peter-Crawley commented
> I'm a little confused as to why this is causing issues now, when it didn't before I merged main with [e1a5265](https://github.com/HorizonsEndMC/Ion/commit/e1a5265c96ac48963006b0ed83c31200928194e3) ![image](https://user-images.githubusercontent.com/66213737/150884483-63c5b6d5-ecf5-4f5c-b1db-024ecceae3dc.png)
> 
> I look at what it's complaining about and all three are ![image](https://user-images.githubusercontent.com/66213737/150884536-bee5f3ee-bdd5-41f7-99ff-4484486c5478.png)
> 
> I'm more than a little confused

My solution is to just to throw in some ? and some !! (which is what I just did in a commit) and fix it if it breaks.

2022-01-27 01:21 UTC, trainb0y1 commented
How should I do the coloring on item names? The way SL did it was pretty annoying in that some names weren't that legible (think power drill, "drill" was in really dark gray), and I think a consistent color scheme would be nice.

2022-01-27 20:22 UTC, Peter-Crawley commented
> How should I do the coloring on item names? The way SL did it was pretty annoying in that some names weren't that legible (think power drill, "drill" was in really dark gray), and I think a consistent color scheme would be nice.

Idk just use red if something is a weapon and orange if its not or something

2022-01-27 20:34 UTC, trainb0y1 commented
Alright, I'll do that

2022-01-28 01:38 UTC, trainb0y1 commented
>  * No colouring on the item names  

Fixed with https://github.com/HorizonsEndMC/Ion/pull/72/commits/a7be7a16c6e03c82d27f161cea2b8243b0bf84a2

2022-01-28 01:48 UTC, Peter-Crawley requested changes

2022-01-28 01:48 UTC, Peter-Crawley commented on server/Ion/src/main/kotlin/net/horizonsend/ion/server/commands/misc/ItemUsesCommand.kt
> +object ItemUsesCommand : SLCommand() {
Why does this command need to exist?

2022-01-28 01:48 UTC, Peter-Crawley commented on server/Ion/src/main/kotlin/net/horizonsend/ion/server/customitems/CustomItems.kt
> +		 * It is recommended to use [CustomItems.get] or [ItemStack.customItem] instead for
use the replaceWith javadoc.

2022-01-28 01:48 UTC, Peter-Crawley commented on server/Ion/src/main/kotlin/net/horizonsend/ion/server/customitems/EnergySwords.kt
> +	@Suppress("DEPRECATION") // I want to use .capitalize() lol
👀

no.

2022-01-28 01:48 UTC, Peter-Crawley commented on server/StarLegacy/src/main/kotlin/net/starlegacy/command/misc/BatteryCommand.kt
>  	private fun getPowerableItemInHand(sender: Player): ItemStack {
Honestly these commands are fairly redundent and can be scrapped as well

2022-01-28 01:59 UTC, trainb0y1 commented on server/Ion/src/main/kotlin/net/horizonsend/ion/server/commands/misc/ItemUsesCommand.kt
> +object ItemUsesCommand : SLCommand() {
it doesn't really, I guess anyone who would have access to that could just give themselves a new one
it was mostly for debugging
Should I remove it?

2022-01-28 01:59 UTC, trainb0y1 commented on server/Ion/src/main/kotlin/net/horizonsend/ion/server/customitems/EnergySwords.kt
> +	@Suppress("DEPRECATION") // I want to use .capitalize() lol
...sigh. One sec...

2022-01-28 01:59 UTC, trainb0y1 commented on server/StarLegacy/src/main/kotlin/net/starlegacy/command/misc/BatteryCommand.kt
>  	private fun getPowerableItemInHand(sender: Player): ItemStack {
Ok

2022-01-28 02:07 UTC, trainb0y1 commented on server/StarLegacy/src/main/kotlin/net/starlegacy/command/misc/BatteryCommand.kt
>  	private fun getPowerableItemInHand(sender: Player): ItemStack {
Scrapped

2022-01-28 02:07 UTC, trainb0y1 commented on server/Ion/src/main/kotlin/net/horizonsend/ion/server/customitems/EnergySwords.kt
> +	@Suppress("DEPRECATION") // I want to use .capitalize() lol
Well, I did it. `String.captalized()` is now a thing...

2022-01-28 02:09 UTC, trainb0y1 commented on server/Ion/src/main/kotlin/net/horizonsend/ion/server/customitems/CustomItems.kt
> +		 * It is recommended to use [CustomItems.get] or [ItemStack.customItem] instead for
That doesn't seem to be a thing?

2022-01-28 02:09 UTC, trainb0y1 commented on server/Ion/src/main/kotlin/net/horizonsend/ion/server/customitems/CustomItems.kt
> +		 * It is recommended to use [CustomItems.get] or [ItemStack.customItem] instead for
I could just be blind...

2022-01-28 02:09 UTC, trainb0y1 commented on server/Ion/src/main/kotlin/net/horizonsend/ion/server/commands/misc/ItemUsesCommand.kt
> +object ItemUsesCommand : SLCommand() {
Removed

2022-01-29 14:29 UTC, Peter-Crawley approved these changes

2022-01-29 14:42 UTC, Peter-Crawley commented
Was hoping to rebase merge this but It borked my local repo so /shrug

2022-01-29 14:42 UTC, merged